# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class InlineResponse2001(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, checked_out: bool=None, session_duration: int=None, number_of_operations: int=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger

        :param checked_out: The checked_out of this InlineResponse2001.  # noqa: E501
        :type checked_out: bool
        :param session_duration: The session_duration of this InlineResponse2001.  # noqa: E501
        :type session_duration: int
        :param number_of_operations: The number_of_operations of this InlineResponse2001.  # noqa: E501
        :type number_of_operations: int
        """
        self.swagger_types = {
            'checked_out': bool,
            'session_duration': int,
            'number_of_operations': int
        }

        self.attribute_map = {
            'checked_out': 'checkedOut',
            'session_duration': 'sessionDuration',
            'number_of_operations': 'numberOfOperations'
        }

        self._checked_out = checked_out
        self._session_duration = session_duration
        self._number_of_operations = number_of_operations

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2001':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_1 of this InlineResponse2001.  # noqa: E501
        :rtype: InlineResponse2001
        """
        return util.deserialize_model(dikt, cls)

    @property
    def checked_out(self) -> bool:
        """Gets the checked_out of this InlineResponse2001.


        :return: The checked_out of this InlineResponse2001.
        :rtype: bool
        """
        return self._checked_out

    @checked_out.setter
    def checked_out(self, checked_out: bool):
        """Sets the checked_out of this InlineResponse2001.


        :param checked_out: The checked_out of this InlineResponse2001.
        :type checked_out: bool
        """

        self._checked_out = checked_out

    @property
    def session_duration(self) -> int:
        """Gets the session_duration of this InlineResponse2001.

        The session duration in seconds  # noqa: E501

        :return: The session_duration of this InlineResponse2001.
        :rtype: int
        """
        return self._session_duration

    @session_duration.setter
    def session_duration(self, session_duration: int):
        """Sets the session_duration of this InlineResponse2001.

        The session duration in seconds  # noqa: E501

        :param session_duration: The session_duration of this InlineResponse2001.
        :type session_duration: int
        """

        self._session_duration = session_duration

    @property
    def number_of_operations(self) -> int:
        """Gets the number_of_operations of this InlineResponse2001.

        The number of arm movements performed during the session  # noqa: E501

        :return: The number_of_operations of this InlineResponse2001.
        :rtype: int
        """
        return self._number_of_operations

    @number_of_operations.setter
    def number_of_operations(self, number_of_operations: int):
        """Sets the number_of_operations of this InlineResponse2001.

        The number of arm movements performed during the session  # noqa: E501

        :param number_of_operations: The number_of_operations of this InlineResponse2001.
        :type number_of_operations: int
        """

        self._number_of_operations = number_of_operations
